"""init plugin runtime init

Revision ID: 0001
Revises: 
Create Date: 2026-01-05 17:50:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pg_installed_plugins',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('plugin_id', sa.String(length=255), nullable=False),
        sa.Column('project_id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('version', sa.String(length=50), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('author', sa.String(length=255), nullable=True),
        sa.Column('install_type', sa.String(length=50), nullable=False),
        sa.Column('source_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('build_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('runtime_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('install_path', sa.String(length=512), nullable=True),
        sa.Column('pid', sa.Integer(), nullable=True),
        sa.Column('last_error', sa.Text(), nullable=True),
        sa.Column('installed_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pg_installed_plugins_plugin_id'), 'pg_installed_plugins', ['plugin_id'], unique=False)
    op.create_index(op.f('ix_pg_installed_plugins_project_id'), 'pg_installed_plugins', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pg_installed_plugins_project_id'), table_name='pg_installed_plugins')
    op.drop_index(op.f('ix_pg_installed_plugins_plugin_id'), table_name='pg_installed_plugins')
    op.drop_table('pg_installed_plugins')
    # ### end Alembic commands ###

